### ISSUE TITLE
Mapping HL7-FHIR model on NGSI-LD

### ISSUE THREAD

**Issue by agaldemas-eridanis** [smart-data-models/incubated#114]
Hello @albertoabellagarcia 

I took some time to think about the subject, and have some proposal, to enhance, and simplify the produced entities json schemas.

First find hereafter a new schema :

![HL7-FHIR2NGSI drawio](https://user-images.githubusercontent.com/82389794/224273382-f63dae39-052a-4874-851b-6aab44119a07.png)

I tried to enumerate some rules for the transformation of HL7-FHIR json schema into NGSI-LD Fiware smart data models:

1. Split base definitions in separated schema's files (one per definition, such as Extension, Meta, Element...
2. Split resources types in separated schema's files (one per Resource type, ex Patient, Practitioner...)
3. update reference in resources types to match ngsi-ld schemas organization, using `$ref: #/<path-to-json-schema>`
4. to manage extension recursion, manage it through NGSI entities of type: Extension, through relationship, to avoid validation infinite loop.

Hope you'll have time to watch my post, before our meeting, CU later

**Comment by albertoabellagarcia** [comment]
We need a dedicated session for this. please use https://calendly.com/smartdatamodels

**Comment by albertoabellagarcia** [comment]
I mostly agree with the contribution. Anyhow it does not solve the infinite recursion problem. independently where these basic definitions are included (make sense what you suggest). But the problem is the infinite recursion. we have limited to 4 levels. I hardly expect anybody beyond 2nd level. And with that the Data models are huge. We keep on working on that.

**Comment by agaldemas-eridanis** [comment]
Hi @albertoabellagarcia the infinite recursion occurs for the `extension` prpoerty of HL7 resource, what if each extension is considered as an entity in relation with the resource ?

It could simplify the schema of each entity type, if `extension` property is modeled with a relationship, even in an Extension entity, it should not cause any recursion issue,

in addition extension may need several types of entities, not known in the global HL7 schema, which push to the use of relationship to entities, to be able to materialize several types of extensions, through different types of entities.

I'm available to discuss about this, whenever you want @albertoabellagarcia...
