### ISSUE TITLE
SimulationResult doesn't allow storage of most simulation outputs

### ISSUE THREAD

**Issue by csweetapple** [smart-data-models/incubated#30]
`SimuationResult` allows simulation results to be stored using the `outputParameters` property and _water attribute_ sub-property. This _water attribute_ sub-property must be a water attribute issued from the Water Network Managemement data model.

Outputs from an EPANET simulation include pressure, demand, head, quality, and source mass inflow for nodes, and flow, velocity and quality for links. However, these are not (all) currently defined as water attributes in the Water Network Managemement data model (since this data model was designed to capture all the _inputs_ to a simulation, not _outputs_). Therefore, it is not currently possible to store most of the simulation outputs using the `SimulationResult` data model.

To overcome this, it is necessary to ensure that `Pipe`, `Pump` and `Valve` entities contain the following attributes:
* `flow`
* `velocity`
* `quality`

And that `Junction`, `Tank` and `Reservoir` entities contain:
* `demand`
* `head`
* `quality` 
* `sourceMassInflow`

This might be achieved by renaming the attributes being added in https://github.com/smart-data-models/dataModel.WaterNetworkManagement/pull/16.

**Comment by albertoabellagarcia** [comment]
Plese see this [PR](https://github.com/smart-data-models/incubated/commit/98504607d7379b2b65522c926d719f3e12bca620) I guess this tackles the issue.
