### ISSUE TITLE
WaterNetworkManagement2 `inputParameter` definition wrong

### ISSUE THREAD

**Issue by csweetapple** [smart-data-models/incubated#36]
@albertoabellagarcia 

The definition of the `inputParameter` property in the SimulationScenario schema needs changing.

Looking back at the original spec.md, the following two sub-properties were described:

> inputParameter : Description of the set of modifications to be applied to the network for the simulation
>     * water attribute: A sub-property. A water attribute issued from the Water network managemement model. It follows fully this data model and it could be a property or a relationship . It is the attribute that will be modified by the simulation.
>     * targetURI: A sub-Relationship of the ~water attribute~ inputParameter. It presents the target water node or link that will handle the modification.

The water attribute could be any attirbute from the corresponding data model of the network component that is being changed (e.g. `setting`, `diameter`, `initialQuality`...), and might also have sub-properties (if defined in the corresponding data model - e.g. for a node's `demandCategory`).

The `targetURI` was originally defined as a a sub-property of the water attribute, but I think on reflection it would be better as a sub-property of `inputParameter` instead, since the definition of the water attribute should match that in the corresponding component's data model.

E.g. if the setting of a valve and demand of a junction are modified in a simulation, these might be defined as follows:

```
    "inputParameters": [
        {
            "type": "Property",
            "value": "Modification 1",
            "setting": {
                "type": "Property",
                "value": 50                
            },
            "targetURI": {
                "type": "Property",
                "value": "urn:ngsi-ld:Valve:V1"
            },
            "datasetId": "urn:ngsi-ld:Dataset:ValveSetting"
        },
        {
            "type": "Property",
            "value": "Modification 2",
            "demandCategory": {
                "type": "Property",
                "value": "agriculture demand",
                "baseDemand": {
                    "type": "Property",
                    "value": "1.763868462",
                    "unitCode": "MQS"
                },
                "demandPattern": {
                    "type": "Relationship",
                    "object": "urn:ngsi-ld:Pattern:P1"
                }
            },
            "targetURI": {
                "type": "Property",
                "value": "urn:ngsi-ld:Junction:J1"
            },
            "datasetId": "urn:ngsi-ld:Dataset:JunctionDemand"
        }
    ],
```

In the schema at present, `inputParameter` has been given a `setting` sub-property, which is wrong as any water network management component property (water attribute) could be used (`setting` is just one very specific example). However, I'm not sure how this should be defined in the schema.

Lastly, would it be simpler to use an array here (as for the `operationalControl` property) rather than multiple instances usingdatasetID?

**Comment by csweetapple** [comment]
To summarise, three issues:
1. It should be possible to include any water attribute as a sub-property, not just `setting`
2. ~`targetURI` may be better as a sub-property of `inputParameter` rather than a sub-property of the water attribute~ *Resolved*
3. ~For multiple `inputParamter`s, would it be simpler to use an array rather than datasetID?~ *Resolved*

**Comment by albertoabellagarcia** [comment]
See the new [PR](https://github.com/smart-data-models/incubated/blob/master/WaterNetworkManagement2/SimulationScenario/schema.json), I guess it tackles the issue.

**Comment by csweetapple** [comment]
This still has a `setting` property, which is wrong. `setting` is just one specific example of a water attribute that could be a property of `inputParameter`. Other examples include anything that is a property of the entity described by the `targetURI`. This would be a long list and I guess we don't want to redefine every one individually if there is any other way around it, especially as this would be bad for maintainability if any changes are made in the other data models.

```
        "inputParameter": {
          "type": "array",
          "description": "Property. Model:'https://Text'. Description of the set of modifications to be applied to the network for the simulation",
          "items": {
            "type": "object",
            "properties": {
              "parameterName": {
                "type": "string"
              },
              "setting": {                <--- WRONG: We need to be able to specify any water attribute, not just "setting" specifically
                "type": "number"
              },
              "targetURI": {
                "anyOf": [
                  {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 256,
                    "pattern": "^[\\w\\-\\.\\{\\}\\$\\+\\*\\[\\]`|~^@!,:\\\\]+$"
                  },
                  {
                    "type": "string",
                    "format": "uri"
                  }
                ],
                "description": "Relationship. Model:'https://schema.org/URL'. URI of network component with property modified in simulation. A sub-relationship of the Property water attribute."
              }
            }
          }
        }
```

**Comment by albertoabellagarcia** [comment]
now its fixed. see new PR
