### ISSUE TITLE
Incubated contribution: Drug

### ISSUE THREAD

**Issue by fdrobnic** [smart-data-models/incubated#48]
Hello @albertoabellagarcia!

I have made a first iteration of an exercise to submit a new data model: incubated/Drug.

Could you please review and comment it?

PS: I have inadvertently commit it directly to the master branch, I hope it won't cause much trouble.

**Comment by albertoabellagarcia** [comment]
quite nice and mostly right (as exercise) 
1) Review the Model coding in the descriptions, see contribution manual.
2) For examples include values with a meaningful content (not just the random values generated) 
3) The example https://github.com/smart-data-models/incubated/blob/master/Drug/examples/example-normalized.jsonld (it is not a valid normalized payload) (I guess the name is changed with example.jsonld)
4) https://github.com/smart-data-models/incubated/blob/master/Drug/examples/example-normalized.json is not a valid normalized ngsi v2 payload. 
Thanks

**Comment by fdrobnic** [comment]
Amended.

It is based on [https://www.schema.org/Drug](https://www.schema.org/Drug). Can this fact be mentioned somewhere, maybe in the schema description?

**Comment by albertoabellagarcia** [comment]
Definitely, it is the kind of thing to be included in the notes.yaml file, please add it to your model.
