### ISSUE TITLE
Incubated: CPSV-AP, Criterion Requirement type

### ISSUE THREAD

**Issue by flopezag** [smart-data-models/incubated#82]
Currently there is no details about the property Criterion Requirement type. The version [v2.2.1](https://github.com/catalogue-of-services-isa/CPSV-AP/blob/master/releases/2.2.1/SC2015DI07446_D02.02_CPSV-AP-2.2.1_v1.00.pdf) only specifies TBC (see section 3.8.3 Type and section 4 Recommended Controlled Vocabularies in page 39), and [v3.0.0](https://catalogue-of-services-isa.github.io/CPSV-AP/releases/3.0.0) there is no reference to the possible values of it.

**Comment by albertoabellagarcia** [comment]
please could you provide a specific link where this comment apply?

**Comment by flopezag** [comment]
I updated the description to add links to the defined specification

**Comment by albertoabellagarcia** [comment]
Reopen if anything else is missing
