### ISSUE TITLE
404 Page not found!

### ISSUE THREAD

**Issue by flopezag** [smart-data-models/incubated#84]
When I try to access to the url https://smart-data-models.github.io/data-models/templates/dataModel/CURRENT_ADOPTERS.yaml, I obtain a 404 message, page not found.

This link is described in the ADOPTERS.yaml file of some data models (e.g. [WaterQualityObserved/ADOPTERS.yaml](https://github.com/smart-data-models/dataModel.WaterQuality/blob/master/WaterQualityObserved/ADOPTERS.yaml)

**Comment by albertoabellagarcia** [comment]
thanks.
solved
